import React, { useState } from 'react';
import { useJarvis } from '../context/JarvisContext';
import JarvisCalendar from './JarvisCalendar';
import tForceLogo from '../assets/Tforcelogo1.png'; // ⚠️ Make sure image is in src/assets/

const IncidentLogPanel = ({ onSetAlarm }) => {
  const { playSound, speak, setActiveMode, user } = useJarvis();
  
  const [logs, setLogs] = useState([
    { id: 1, time: '09:00', type: 'ROUTINE', note: 'Shift start. Perimeter secure.' },
    { id: 2, time: '11:30', type: 'CHECK', note: 'North Gate sensors calibrated [2025-12-14].' },
  ]);
  
  const [inputText, setInputText] = useState('');
  const [editingId, setEditingId] = useState(null);
  const [showCalendar, setShowCalendar] = useState(false);

  const extractTime = (text) => {
      const timeRegex = /([01]?[0-9]|2[0-3]):[0-5][0-9]/;
      const match = text.match(timeRegex);
      return match ? match[0] : null;
  };

  const extractDate = (text) => {
      const dateRegex = /\[(\d{4}-\d{2}-\d{2})\]/;
      const match = text.match(dateRegex);
      return match ? match[1] : null;
  };

  // --- 🖨️ REPORT GENERATION ENGINE ---
  const handlePrintReport = (e) => {
      if (e) e.stopPropagation();
      playSound('click');
      speak("Compiling End of Shift Report. Stand by.");

      // 1. Create a new window for printing
      const printWindow = window.open('', '_blank');
      
      // 2. Generate the HTML for the report
      const dateStr = new Date().toLocaleDateString('en-GB');
      
      const htmlContent = `
        <html>
        <head>
          <title>T-FORCE SECURITY REPORT - ${dateStr}</title>
          <style>
            body { font-family: 'Arial', sans-serif; padding: 40px; color: #000; }
            .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #cc0000; padding-bottom: 20px; margin-bottom: 30px; }
            .logo { height: 80px; }
            .title-block { text-align: right; }
            h1 { margin: 0; font-size: 24px; color: #000; text-transform: uppercase; }
            h2 { margin: 5px 0 0 0; font-size: 14px; color: #666; font-weight: normal; }
            
            .meta-table { width: 100%; margin-bottom: 30px; border-collapse: collapse; }
            .meta-table td { padding: 8px; border: 1px solid #ddd; }
            .label { font-weight: bold; background-color: #f5f5f5; width: 150px; }
            
            .log-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .log-table th { background-color: #cc0000; color: white; padding: 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
            .log-table td { border-bottom: 1px solid #ddd; padding: 12px; font-size: 14px; vertical-align: top; }
            .log-table tr:nth-child(even) { background-color: #f9f9f9; }
            
            .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; display: flex; justify-content: space-between; }
            .signature { margin-top: 40px; }
            .sig-line { width: 200px; border-top: 1px solid #000; margin-top: 40px; padding-top: 5px; font-size: 12px; text-align: center; }
          </style>
        </head>
        <body>
          
          <div class="header">
            <img src="${tForceLogo}" class="logo" alt="T-FORCE LOGO" />
            <div class="title-block">
              <h1>End of Shift Report</h1>
              <h2>OFFICIAL SECURITY RECORD</h2>
            </div>
          </div>

          <table class="meta-table">
            <tr>
              <td class="label">DATE:</td>
              <td>${dateStr}</td>
              <td class="label">LOCATION:</td>
              <td>MYKONOS HQ</td>
            </tr>
            <tr>
              <td class="label">OFFICER:</td>
              <td>${user.name.toUpperCase()}</td>
              <td class="label">SHIFT:</td>
              <td>08:00 - 20:00 (Standard)</td>
            </tr>
          </table>

          <table class="log-table">
            <thead>
              <tr>
                <th width="100">TIME</th>
                <th width="120">TYPE</th>
                <th>DETAILS</th>
              </tr>
            </thead>
            <tbody>
              ${logs.map(log => `
                <tr>
                  <td><strong>${log.time}</strong></td>
                  <td><span style="border: 1px solid #ccc; padding: 2px 6px; font-size: 10px; border-radius: 4px;">${log.type}</span></td>
                  <td>${log.note}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            <div>GENERATED BY JARVIS SYSTEM | T-FORCE SECURITY</div>
            <div class="signature">
              <div class="sig-line">Officer Signature</div>
            </div>
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
        </html>
      `;

      printWindow.document.write(htmlContent);
      printWindow.document.close();
  };

  const handleEmailReport = (e) => {
      if (e) e.stopPropagation();
      playSound('click');
      speak("Opening mail client.");

      const subject = `T-FORCE SECURITY REPORT - ${new Date().toLocaleDateString()}`;
      let body = `OFFICER: ${user.name}\nDATE: ${new Date().toLocaleDateString()}\n\nLOG ENTRIES:\n--------------------------------\n`;
      
      logs.forEach(log => {
          body += `[${log.time}] - ${log.type}: ${log.note}\n`;
      });

      body += `\n--------------------------------\nEND OF REPORT`;

      window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);
  };

  // --- STANDARD ACTIONS ---
  const stopAndRun = (e, callback) => {
      if (e) {
          e.preventDefault();
          e.stopPropagation();
          e.nativeEvent.stopImmediatePropagation();
      }
      callback();
  };

  const handleDateSelect = (dateString) => {
      playSound('click');
      const newText = inputText + ` [${dateString}]`;
      setInputText(newText);
      setShowCalendar(false);
  };

  const handleSubmit = (e) => stopAndRun(e, () => {
    if (!inputText.trim()) return;
    playSound('click');

    const now = new Date();
    const timeString = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;

    if (editingId) {
        setLogs(logs.map(log => 
            log.id === editingId ? { ...log, note: inputText } : log
        ));
        speak("Entry updated.");
        setEditingId(null);
    } else {
        const newLog = {
            id: Date.now(),
            time: timeString,
            type: 'ENTRY',
            note: inputText
        };
        setLogs([newLog, ...logs]);
        
        const detectedTime = extractTime(newLog.note);
        if (detectedTime) speak(`Log saved.`);
        else speak("Log entry saved.");
    }
    setInputText('');
  });

  const handleDelete = (e, id) => stopAndRun(e, () => {
      playSound('click');
      setLogs(logs.filter(log => log.id !== id));
  });

  const handleEdit = (e, log) => stopAndRun(e, () => {
      playSound('click');
      setInputText(log.note);
      setEditingId(log.id);
  });

  const handleAlarm = (e, log, isRecurring) => stopAndRun(e, () => {
      const targetTime = extractTime(log.note);
      const targetDate = extractDate(log.note); 
      
      if (log.type === 'ROUTINE' || targetTime) {
          const alarmTime = targetTime || log.time; 
          playSound('click');
          
          if (isRecurring) speak(`Setting DAILY alarm for ${alarmTime}.`);
          else if (targetDate) speak(`Setting alarm for ${targetDate} at ${alarmTime}.`);
          else speak(`Setting alarm for ${alarmTime}.`);
          
          if (onSetAlarm) {
              onSetAlarm({ 
                  time: alarmTime, 
                  date: targetDate, 
                  note: log.note, 
                  isRecurring: isRecurring 
              });
          }
      } else {
          speak("No time detected in this entry.");
      }
  });

  const handleClose = (e) => stopAndRun(e, () => {
      playSound('click');
      setActiveMode('HOME');
  });

  return (
    <div className="absolute inset-0 flex items-center justify-center p-4 pointer-events-auto" style={{ zIndex: 100 }}>
      
      <div className="absolute inset-0 bg-black/80 backdrop-blur-md cursor-pointer" onClick={handleClose}></div>

      {showCalendar && (
          <JarvisCalendar 
            onDateSelect={handleDateSelect} 
            onClose={() => setShowCalendar(false)} 
          />
      )}

      <div 
        onClick={(e) => e.stopPropagation()} 
        className="relative w-full max-w-md h-[85vh] bg-black border border-cyan/30 rounded-lg shadow-[0_0_50px_rgba(0,229,255,0.2)] flex flex-col overflow-hidden cursor-default"
        style={{ pointerEvents: 'auto' }}
      >
        
        {/* HEADER with REPORT TOOLS */}
        <div className="bg-cyan/10 p-3 border-b border-cyan/30 flex justify-between items-center shrink-0">
          <div>
            <h2 className="font-orbitron font-bold text-cyan text-lg tracking-widest">INCIDENT LOG</h2>
            <div className="flex gap-2 mt-1">
                {/* 🖨️ PRINT BUTTON */}
                <button 
                    onClick={handlePrintReport}
                    className="text-[10px] bg-cyan/20 hover:bg-cyan/40 text-cyan border border-cyan/50 px-2 py-1 rounded flex items-center gap-1 transition-all"
                >
                    <i className="fas fa-print"></i> PRINT REPORT
                </button>
                {/* 📧 EMAIL BUTTON */}
                <button 
                    onClick={handleEmailReport}
                    className="text-[10px] bg-cyan/20 hover:bg-cyan/40 text-cyan border border-cyan/50 px-2 py-1 rounded flex items-center gap-1 transition-all"
                >
                    <i className="fas fa-envelope"></i> EMAIL
                </button>
            </div>
          </div>
          
          <button onClick={handleClose} className="w-8 h-8 flex items-center justify-center border border-cyan/30 bg-black rounded hover:bg-red-500/20 hover:text-red-500 transition-all z-50 cursor-pointer">
            <i className="fas fa-times text-lg"></i>
          </button>
        </div>

        {/* LOG LIST */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar relative">
          {logs.map((log) => {
            const hasTime = extractTime(log.note) || log.type === 'ROUTINE';
            return (
                <div key={log.id} className="bg-gray-900/80 border border-cyan/20 p-3 rounded transition-all relative group">
                    <div className="flex justify-between items-start mb-2 pointer-events-none">
                        <span className="font-mono text-xs text-emerald-400 font-bold">[{log.time}]</span>
                        <span className="font-mono text-[10px] text-cyan/50 tracking-wider border border-cyan/30 px-1 rounded">{log.type}</span>
                    </div>
                    <p className="text-cyan/90 font-sans text-sm leading-relaxed mb-10 pointer-events-none">{log.note}</p>
                    
                    <div className="absolute bottom-2 right-2 flex gap-3 z-20 bg-black/60 px-2 py-1 rounded border border-cyan/10">
                        <button onClick={(e) => handleEdit(e, log)} className="text-cyan hover:text-white text-sm w-8 h-8 flex items-center justify-center border border-cyan/30 rounded cursor-pointer active:bg-cyan/20">
                            <i className="fas fa-pen"></i>
                        </button>
                        <button onClick={(e) => handleDelete(e, log.id)} className="text-cyan hover:text-red-500 text-sm w-8 h-8 flex items-center justify-center border border-cyan/30 rounded cursor-pointer active:bg-red-500/20">
                            <i className="fas fa-trash"></i>
                        </button>
                        {hasTime && (
                            <>
                                <div className="w-[1px] h-6 bg-cyan/30 self-center"></div>
                                <button onClick={(e) => handleAlarm(e, log, false)} className="text-cyan hover:text-yellow-400 text-sm w-8 h-8 flex items-center justify-center border border-cyan/30 rounded cursor-pointer active:bg-yellow-400/20">
                                    <i className="fas fa-bell"></i>
                                </button>
                                <button onClick={(e) => handleAlarm(e, log, true)} className="text-cyan hover:text-purple-400 text-sm w-8 h-8 flex items-center justify-center border border-cyan/30 rounded cursor-pointer active:bg-purple-400/20">
                                    <i className="fas fa-sync"></i>
                                </button>
                            </>
                        )}
                    </div>
                </div>
            );
          })}
        </div>

        {/* INPUT AREA */}
        <div className="p-4 bg-cyan/5 border-t border-cyan/30 shrink-0 relative z-50">
          <div className="relative">
              <textarea 
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onClick={(e) => e.stopPropagation()}
                onFocus={(e) => e.stopPropagation()}
                placeholder="Ex: Meeting at 14:00..."
                className={`w-full bg-black border rounded p-3 text-cyan text-sm focus:outline-none transition-colors h-24 resize-none font-mono cursor-text relative z-50 pr-10
                    ${editingId ? 'border-yellow-500/50 shadow-[0_0_10px_rgba(234,179,8,0.2)]' : 'border-cyan/30 focus:border-cyan'}
                `}
              />
              <button 
                onClick={(e) => stopAndRun(e, () => setShowCalendar(!showCalendar))}
                className="absolute top-2 right-2 text-cyan hover:text-white z-[60] p-2 cursor-pointer"
                title="Select Date"
              >
                  <i className="far fa-calendar-alt text-lg"></i>
              </button>
          </div>

          <div className="flex gap-2 mt-3">
              {editingId && (
                  <button onClick={(e) => { e.stopPropagation(); setEditingId(null); setInputText(''); }} className="px-4 py-3 bg-red-900/30 text-red-400 border border-red-900/50 rounded font-orbitron font-bold text-xs hover:bg-red-900/50 cursor-pointer relative z-50">
                      CANCEL
                  </button>
              )}
              <button onClick={handleSubmit} className={`flex-1 py-3 border text-black font-orbitron font-bold rounded transition-all active:scale-95 flex items-center justify-center gap-2 cursor-pointer relative z-50
                  ${editingId ? 'bg-yellow-500 hover:bg-yellow-400 border-yellow-500' : 'bg-cyan hover:bg-cyan/80 border-cyan'}
              `}>
                <i className={`fas ${editingId ? 'fa-check' : 'fa-save'}`}></i> 
                {editingId ? "UPDATE ENTRY" : "SUBMIT ENTRY"}
              </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default IncidentLogPanel;