import React, { useState } from 'react';
import { useJarvis } from '../context/JarvisContext';
import { jsPDF } from 'jspdf';

const OpsPanel = () => {
  const { incidentLog, addIncident, deleteIncident, setActiveMode, playSound, speak } = useJarvis();
  const [formData, setFormData] = useState({ title: '', location: '', details: '', severity: 'Low' });
  const [advice, setAdvice] = useState(null);

  // KEYWORD ANALYSIS
  const analyzeThreat = (text) => {
    const t = text.toLowerCase();
    let suggestions = [];
    
    if (t.includes('fight') || t.includes('brawl')) suggestions.push("• Increase security presence in sector.");
    if (t.includes('weapon') || t.includes('gun') || t.includes('knife')) suggestions.push("• CRITICAL: Contact Police immediately. Lockdown perimeter.");
    if (t.includes('iron') || t.includes('knuckle')) suggestions.push("• MANDATORY: Metal detector wands at entry.");
    if (t.includes('drug') || t.includes('pill')) suggestions.push("• Search bathrooms and VIP areas.");
    if (t.includes('overcrowd') || t.includes('full')) suggestions.push("• Halt entry. Check fire exits.");

    if (suggestions.length > 0) {
        setAdvice(suggestions);
        if (t.includes('weapon')) speak("High alert. Weapon protocol suggested.");
    } else {
        setAdvice(null);
    }
  };

  const handleTextChange = (e) => {
    setFormData({ ...formData, details: e.target.value });
    analyzeThreat(e.target.value);
  };

  const handleSave = () => {
    if (!formData.title) return;
    addIncident(formData);
    setFormData({ title: '', location: '', details: '', severity: 'Low' });
    setAdvice(null);
  };

  // PDF GENERATOR
  const generatePDF = (incident) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 40, 'F'); // Black header
    doc.setTextColor(0, 229, 255); // Cyan
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("T-FORCE SECURITY SITREP", 15, 20);
    doc.setFontSize(10);
    doc.text("INTERNAL CLASSIFIED REPORT", 15, 30);

    // Content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text(`INCIDENT: ${incident.title}`, 15, 60);
    doc.setFontSize(12);
    doc.text(`DATE: ${incident.date}`, 15, 70);
    doc.text(`LOCATION: ${incident.location}`, 15, 80);
    doc.text(`SEVERITY: ${incident.severity.toUpperCase()}`, 15, 90);
    
    doc.line(15, 95, 195, 95);
    
    doc.setFont("helvetica", "normal");
    doc.text("DETAILS:", 15, 110);
    const splitText = doc.splitTextToSize(incident.details, 180);
    doc.text(splitText, 15, 120);

    // Footer
    doc.setTextColor(150);
    doc.setFontSize(10);
    doc.text("Generated by JARVIS Operational Unit", 15, 280);

    doc.save(`T-Force_Report_${incident.id}.pdf`);
    speak("Report compiled and downloaded.");
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/95 backdrop-blur-xl flex flex-col animate-slide-up">
      
      {/* Header */}
      <div className="flex justify-between items-center p-6 border-b border-cyan/30">
        <div className="flex items-center gap-3">
            <i className="fas fa-file-alt text-cyan text-xl animate-pulse"></i>
            <h2 className="text-cyan font-orbitron text-xl tracking-widest">INCIDENT LOG</h2>
        </div>
        <button onClick={() => { playSound('click'); setActiveMode("HOME"); }} className="text-cyan hover:text-white">
          <i className="fas fa-times text-2xl"></i>
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 no-scrollbar">
        
        {/* INPUT FORM */}
        <div className="bg-cyan/5 border border-cyan/30 p-4 rounded mb-6">
            <div className="mb-4">
                <label className="text-cyan-dim text-xs font-mono">INCIDENT TYPE</label>
                <input type="text" value={formData.title} onChange={e => setFormData({...formData, title: e.target.value})} className="w-full bg-black border border-cyan/30 p-2 text-cyan outline-none focus:border-cyan" placeholder="E.g., Fight at Bar" />
            </div>
            <div className="flex gap-4 mb-4">
                <div className="flex-1">
                    <label className="text-cyan-dim text-xs font-mono">LOCATION</label>
                    <input type="text" value={formData.location} onChange={e => setFormData({...formData, location: e.target.value})} className="w-full bg-black border border-cyan/30 p-2 text-cyan outline-none" placeholder="Mykonos Club" />
                </div>
                <div>
                    <label className="text-cyan-dim text-xs font-mono">SEVERITY</label>
                    <select value={formData.severity} onChange={e => setFormData({...formData, severity: e.target.value})} className="w-full bg-black border border-cyan/30 p-2 text-cyan outline-none">
                        <option>Low</option>
                        <option>Medium</option>
                        <option>High</option>
                        <option>Critical</option>
                    </select>
                </div>
            </div>
            <div className="mb-4">
                <label className="text-cyan-dim text-xs font-mono">DETAILS</label>
                <textarea value={formData.details} onChange={handleTextChange} rows="4" className="w-full bg-black border border-cyan/30 p-2 text-cyan outline-none" placeholder="Describe the situation..." />
            </div>

            {/* AI ADVICE BOX */}
            {advice && (
                <div className="mb-4 p-3 bg-red-900/20 border border-red-500/50 rounded">
                    <div className="text-red-500 font-orbitron text-xs mb-2">⚠ TACTICAL ANALYSIS:</div>
                    {advice.map((line, i) => (
                        <div key={i} className="text-red-300 text-xs font-mono">{line}</div>
                    ))}
                </div>
            )}

            <button onClick={handleSave} className="w-full py-3 bg-cyan/20 border border-cyan text-cyan font-orbitron tracking-widest hover:bg-cyan/40">LOG INCIDENT</button>
        </div>

        {/* LOG HISTORY */}
        <div className="space-y-4">
            {incidentLog.map(inc => (
                <div key={inc.id} className="border border-white/10 p-4 rounded bg-white/5 flex justify-between items-start">
                    <div>
                        <div className="text-cyan font-bold font-orbitron">{inc.title}</div>
                        <div className="text-xs text-gray-400 font-mono mb-2">{inc.date} | {inc.location}</div>
                        <div className="text-sm text-gray-300">{inc.details}</div>
                        <div className={`mt-2 text-xs font-bold ${inc.severity === 'Critical' ? 'text-red-500' : 'text-cyan-dim'}`}>LEVEL: {inc.severity.toUpperCase()}</div>
                    </div>
                    <div className="flex flex-col gap-2">
                        <button onClick={() => generatePDF(inc)} className="p-2 border border-cyan/30 text-cyan rounded hover:bg-cyan/10" title="Download PDF"><i className="fas fa-file-pdf"></i></button>
                        <button onClick={() => deleteIncident(inc.id)} className="p-2 border border-red-500/30 text-red-500 rounded hover:bg-red-500/10" title="Delete"><i className="fas fa-trash"></i></button>
                    </div>
                </div>
            ))}
        </div>

      </div>
    </div>
  );
};

export default OpsPanel;